// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfKT7iL7BEzBcXPI0ROsTwd4LXwJnIIPI',
    appId: '1:645973233893:web:69e4829855acaf71d8440c',
    messagingSenderId: '645973233893',
    projectId: 'ovacare-9aa6d',
    authDomain: 'ovacare-9aa6d.firebaseapp.com',
    storageBucket: 'ovacare-9aa6d.firebasestorage.app',
    measurementId: 'G-NXEQKNJPL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSi0TGtNARroHx7X5TCMZ5ArD_Q1DVeoU',
    appId: '1:645973233893:android:c0a7ba1ddf62eb5cd8440c',
    messagingSenderId: '645973233893',
    projectId: 'ovacare-9aa6d',
    storageBucket: 'ovacare-9aa6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBTE9arxY3qMuXE9mnSIsNk1REyUDZsOY',
    appId: '1:645973233893:ios:e8c713bc26097a07d8440c',
    messagingSenderId: '645973233893',
    projectId: 'ovacare-9aa6d',
    storageBucket: 'ovacare-9aa6d.firebasestorage.app',
    iosBundleId: 'com.example.woman1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBTE9arxY3qMuXE9mnSIsNk1REyUDZsOY',
    appId: '1:645973233893:ios:e8c713bc26097a07d8440c',
    messagingSenderId: '645973233893',
    projectId: 'ovacare-9aa6d',
    storageBucket: 'ovacare-9aa6d.firebasestorage.app',
    iosBundleId: 'com.example.woman1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfKT7iL7BEzBcXPI0ROsTwd4LXwJnIIPI',
    appId: '1:645973233893:web:cbe92083206f69a1d8440c',
    messagingSenderId: '645973233893',
    projectId: 'ovacare-9aa6d',
    authDomain: 'ovacare-9aa6d.firebaseapp.com',
    storageBucket: 'ovacare-9aa6d.firebasestorage.app',
    measurementId: 'G-8XXE9KP6LJ',
  );
}
